# Generated by Django 3.0.6 on 2020-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200519_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_image',
            field=models.ImageField(blank=True, db_column='ITEM_IMAGE', null=True, upload_to='profile', verbose_name='IMAGE'),
        ),
    ]
