# Generated by Django 3.0.6 on 2020-05-19 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20200519_1044'),
        ('accounts', '0005_auto_20200519_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.Campground'),
        ),
    ]
