# Generated by Django 3.0.6 on 2020-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200519_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='post',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.TextField(default='Good', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visited_Place',
            field=models.CharField(default='place', max_length=100),
            preserve_default=False,
        ),
    ]
