# Generated by Django 3.0.6 on 2020-05-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_auto_20200519_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campground',
            name='amount_type',
            field=models.CharField(choices=[('week', 'week'), ('day', 'day')], max_length=10),
        ),
    ]
